#!/usr/bin/env python3
"""
BossZhipin (Boss直聘) FastMCP Server
A modern MCP server for BossZhipin recruitment platform
"""

import asyncio
import json
import re
import time
import base64
import threading
from dataclasses import dataclass, asdict
from typing import Any, Dict, List, Optional, Union
from pathlib import Path

import requests
from fastmcp import FastMCP, Context
from starlette.requests import Request
from starlette.responses import JSONResponse, HTMLResponse, FileResponse

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes

from playwright.async_api import async_playwright


@dataclass
class LoginStatus:
    """Login status data model"""
    is_logged_in: bool = False
    cookie: Optional[str] = None
    bst: Optional[str] = None
    qr_id: Optional[str] = None
    login_step: str = "idle"  # idle, qr_generated, scanned, confirmed, security_check, logged_in
    image_url: Optional[str] = None
    error_message: Optional[str] = None


class BossZhipinState:
    """Global state manager for BossZhipin"""

    def __init__(self):
        self.login_status = LoginStatus()
        self.session = None
        self.static_dir = Path("static")
        self.static_dir.mkdir(exist_ok=True)

    def get_session(self) -> requests.Session:
        """Get or create HTTP session"""
        if self.session is None:
            self.session = requests.Session()
            self.session.headers.update({
                'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                'Referer': 'https://www.zhipin.com/web/user/?ka=header-login',
                'Origin': 'https://www.zhipin.com'
            })
        return self.session

    def update_login_status(self, **kwargs):
        """Update login status"""
        for key, value in kwargs.items():
            if hasattr(self.login_status, key):
                setattr(self.login_status, key, value)

    def reset_login(self):
        """Reset login status"""
        self.login_status = LoginStatus()
        if self.session:
            self.session.cookies.clear()
            self.session = None

    def load_cookie_from_file(self, cookie_file: Optional[Union[str, Path]] = None) -> bool:
        """Load login state from boss_cookie.json (generated by login_standalone.py). Returns True if loaded successfully."""
        if cookie_file is None:
            cookie_file = Path(__file__).resolve().parent / "boss_cookie.json"
        path = Path(cookie_file)
        if not path.exists():
            return False
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            cookie = data.get("cookie")
            bst = data.get("bst")
            if not cookie:
                return False
            self.update_login_status(
                is_logged_in=True,
                cookie=cookie,
                bst=bst or "",
                login_step="logged_in",
            )
            if self.session:
                self.session.headers["Cookie"] = cookie
                if bst:
                    self.session.headers["zp_token"] = bst
            return True
        except Exception:
            return False


# Global state instance
state = BossZhipinState()

# Auto-load cookie on startup (useful when logged in via login_standalone.py first)
state.load_cookie_from_file()


def background_scan_monitor(qr_id: str):
    """Monitor scan and confirmation status in a background thread"""
    try:
        session = state.get_session()
        scan_url = f"https://www.zhipin.com/wapi/zppassport/qrcode/scan?uuid={qr_id}"
        confirm_url = f"https://www.zhipin.com/wapi/zppassport/qrcode/scanLogin?qrId={qr_id}&status=1"

        # Phase 1: Wait for scan (long polling)
        print(f"[Monitor] Starting scan monitoring, QR ID: {qr_id}")
        scan_count = 0
        while True:
            if state.login_status.login_step == "logged_in":
                print("[Monitor] Already logged in, stopping monitor")
                return

            try:
                scan_count += 1
                print(f"[Monitor] Scan check #{scan_count}")
                resp = session.get(scan_url, timeout=35)

                if resp.status_code == 200:
                    json_data = resp.json()
                    if json_data.get("scaned"):
                        print("[Monitor] Scan detected, entering confirmation phase")
                        state.update_login_status(login_step="scanned")
                        break
                    elif json_data.get("msg") == "timeout":
                        print(f"[Monitor] Scan timeout, continuing poll... ({scan_count})")
                    else:
                        print(f"[Monitor] Polling... ({scan_count}) - {json_data}")
                else:
                    print(f"[Monitor] Unknown scan status: {resp.status_code}")

            except requests.exceptions.ReadTimeout:
                print(f"[Monitor] Scan read timeout, continuing... ({scan_count})")
                continue
            except Exception as e:
                print(f"[Monitor] Scan check error: {e}")
                time.sleep(2)

            time.sleep(1)

        # Phase 2: Wait for confirmation (long polling)
        if state.login_status.login_step == "scanned":
            print("[Monitor] Starting confirmation monitoring")
            confirm_count = 0
            while True:
                try:
                    confirm_count += 1
                    print(f"[Monitor] Confirm check #{confirm_count}")
                    resp = session.get(confirm_url, timeout=35)

                    if resp.status_code == 200:
                        print("[Monitor] User confirmed login, retrieving cookies")

                        # Generate fp parameter
                        i_str = "8048b8676fb7d3d8952276e6e98e0bde.f2dc7a63c4b0fbfa4b51a07e2710cf83.fef7e750fc3a1e6327e8a880915aee9c.ae00f848beb1aa591d71d5a80dd3bd95"
                        e_b64 = "clRwXUJBK1VKK0k0IWFbbQ=="

                        key_bytes = base64.b64decode(e_b64)
                        plaintext_bytes = i_str.encode('utf-8')
                        iv_bytes = get_random_bytes(16)
                        cipher = AES.new(key_bytes, AES.MODE_CBC, iv_bytes)
                        padded_plaintext = pad(plaintext_bytes, AES.block_size)
                        ciphertext_bytes = cipher.encrypt(padded_plaintext)
                        result_bytes = iv_bytes + ciphertext_bytes
                        fp = base64.b64encode(result_bytes).decode('utf-8')

                        dispatcher_url = f"https://www.zhipin.com/wapi/zppassport/qrcode/dispatcher?qrId={qr_id}&pk=header-login&fp={fp}"
                        cookie_resp = session.get(dispatcher_url, allow_redirects=False)

                        # Parse Set-Cookie headers
                        set_cookie_headers = cookie_resp.headers.get('Set-Cookie', '')
                        cookie_str = ''
                        bst_value = ''

                        if set_cookie_headers:
                            cookies = {}
                            cookie_parts = set_cookie_headers.split(',')
                            for part in cookie_parts:
                                if '=' in part:
                                    name_value = part.strip().split(';')[0].strip()
                                    if '=' in name_value:
                                        name, value = name_value.split('=', 1)
                                        cookies[name.strip()] = value.strip()

                            cookie_str = '; '.join([f"{k}={v}" for k, v in cookies.items()])
                            if 'bst' in cookies:
                                bst_value = cookies['bst']

                        # Phase 3: Complete security check with headless browser
                        print("[Monitor] Starting security check...")
                        state.update_login_status(login_step="security_check")

                        try:
                            loop = asyncio.new_event_loop()
                            asyncio.set_event_loop(loop)
                            final_cookie_str = loop.run_until_complete(
                                BossZhipinAPI.complete_security_check(cookie_str)
                            )
                            loop.close()

                            print("[Monitor] Security check completed")

                            # Update session with final cookies
                            for cookie_pair in final_cookie_str.split('; '):
                                if '=' in cookie_pair:
                                    name, value = cookie_pair.split('=', 1)
                                    session.cookies.set(name, value)

                            state.update_login_status(
                                is_logged_in=True,
                                cookie=final_cookie_str,
                                bst=bst_value,
                                login_step="logged_in"
                            )

                            print("[Monitor] Login successful! Final cookie saved")

                        except Exception as e:
                            print(f"[Monitor] Security check failed, using initial cookie: {e}")

                            if cookie_str:
                                for cookie_pair in cookie_str.split('; '):
                                    if '=' in cookie_pair:
                                        name, value = cookie_pair.split('=', 1)
                                        session.cookies.set(name, value)

                            state.update_login_status(
                                is_logged_in=True,
                                cookie=cookie_str,
                                bst=bst_value,
                                login_step="logged_in"
                            )

                            print("[Monitor] Login successful! Initial cookie saved")

                        return
                    else:
                        json_data = resp.json()
                        if json_data.get("msg") == "timeout":
                            print(f"[Monitor] Confirm timeout, continuing... ({confirm_count})")
                        else:
                            print(f"[Monitor] Polling... ({confirm_count}) - {json_data}")

                except requests.exceptions.ReadTimeout:
                    print(f"[Monitor] Confirm read timeout, continuing... ({confirm_count})")
                    continue
                except Exception as e:
                    print(f"[Monitor] Confirm check error: {e}")
                    time.sleep(2)

                time.sleep(1)

    except Exception as e:
        print(f"[Monitor] Monitor thread error: {e}")
    finally:
        print("[Monitor] Monitor thread ended")


class BossZhipinAPI:
    """BossZhipin API operations class"""

    @staticmethod
    def generate_fp(i_str: str, e_b64: str) -> str:
        """Generate device fingerprint parameter"""
        key_bytes = base64.b64decode(e_b64)
        plaintext_bytes = i_str.encode('utf-8')
        iv_bytes = get_random_bytes(16)

        cipher = AES.new(key_bytes, AES.MODE_CBC, iv_bytes)
        padded_plaintext = pad(plaintext_bytes, AES.block_size)
        ciphertext_bytes = cipher.encrypt(padded_plaintext)

        result_bytes = iv_bytes + ciphertext_bytes
        return base64.b64encode(result_bytes).decode('utf-8')

    @staticmethod
    async def complete_security_check(initial_cookie: str) -> str:
        """Complete security check using headless browser to get final cookie with __zp_stoken__

        Args:
            initial_cookie: Initial cookie from dispatcher API

        Returns:
            Final cookie string containing __zp_stoken__
        """
        security_check_url = (
            "https://www.zhipin.com/web/common/security-check.html?"
            "seed=ttttZij2JIIK%2BxUw73%2B6ZmzsaYKTbDQuIH6OR6Bm54o%3D"
            "&name=e331459e"
            "&ts=1762256958405"
            "&callbackUrl=https%3A%2F%2Fwww.zhipin.com%2Fweb%2Fgeek%2Fjobs"
        )

        print("[Security] Starting security check with headless browser")

        try:
            async with async_playwright() as p:
                browser = await p.chromium.launch(headless=True)
                context = await browser.new_context()

                # Parse and set initial cookies
                cookies = []
                for cookie_pair in initial_cookie.split('; '):
                    if '=' in cookie_pair:
                        name, value = cookie_pair.split('=', 1)
                        cookies.append({
                            'name': name,
                            'value': value,
                            'domain': '.zhipin.com',
                            'path': '/'
                        })

                await context.add_cookies(cookies)
                print(f"[Security] Set {len(cookies)} initial cookies")

                # Access security-check page
                page = await context.new_page()
                print("[Security] Accessing security-check page...")
                await page.goto(security_check_url, wait_until='domcontentloaded')

                # Wait for network idle
                print("[Security] Waiting for network idle...")
                try:
                    await page.wait_for_load_state('networkidle', timeout=30000)
                    print("[Security] Network idle reached")
                except Exception as e:
                    print(f"[Security] Network idle timeout: {e}")

                # Additional wait for JS execution
                print("[Security] Waiting additional 3s for cookies to be set...")
                await asyncio.sleep(3)

                # Get cookies via JavaScript
                print("[Security] Reading cookies via JavaScript...")
                js_cookies = await page.evaluate("() => document.cookie")
                print(f"[Security] JS cookies: {js_cookies[:200]}...")

                # Get cookies via Playwright API
                print("[Security] Getting cookies via Playwright API...")
                final_cookies = await context.cookies()
                playwright_cookie_str = '; '.join([f"{c['name']}={c['value']}" for c in final_cookies])
                print(f"[Security] Playwright cookies: {playwright_cookie_str[:200]}...")

                # Use JS cookies (real browser cookies)
                final_cookie_str = js_cookies

                # Check for __zp_stoken__
                has_stoken = '__zp_stoken__' in js_cookies
                if has_stoken:
                    for cookie_pair in js_cookies.split('; '):
                        if cookie_pair.startswith('__zp_stoken__='):
                            stoken_value = cookie_pair.split('=', 1)[1]
                            print(f"[Security] Got __zp_stoken__: {stoken_value[:20]}...")
                            break
                else:
                    print("[Security] __zp_stoken__ not found")

                print("[Security] Security check completed")

                await browser.close()

                return final_cookie_str

        except Exception as e:
            print(f"[Security] Security check failed: {e}")
            return initial_cookie

    @staticmethod
    async def get_randkey(session: requests.Session) -> str:
        """Get login random key"""
        url = "https://www.zhipin.com/wapi/zppassport/captcha/randkey"
        resp = session.post(url)
        resp.raise_for_status()
        return resp.json()["zpData"]["qrId"]

    @staticmethod
    def get_randkey_sync(session: requests.Session) -> str:
        """Get login random key (sync version)"""
        url = "https://www.zhipin.com/wapi/zppassport/captcha/randkey"
        resp = session.post(url)
        resp.raise_for_status()
        return resp.json()["zpData"]["qrId"]

    @staticmethod
    async def get_qrcode(session: requests.Session, qr_id: str) -> bytes:
        """Get QR code image data"""
        url = f"https://www.zhipin.com/wapi/zpweixin/qrcode/getqrcode?content={qr_id}"
        resp = session.get(url)
        resp.raise_for_status()
        return resp.content

    @staticmethod
    def get_qrcode_sync(session: requests.Session, qr_id: str) -> bytes:
        """Get QR code image data (sync version)"""
        url = f"https://www.zhipin.com/wapi/zpweixin/qrcode/getqrcode?content={qr_id}"
        resp = session.get(url)
        resp.raise_for_status()
        return resp.content

    @staticmethod
    async def check_scan_status(session: requests.Session, qr_id: str) -> int:
        """Check scan status"""
        url = f"https://www.zhipin.com/wapi/zppassport/qrcode/scan?uuid={qr_id}"
        resp = session.get(url, timeout=60)
        return resp.status_code

    @staticmethod
    async def check_login_confirmation(session: requests.Session, qr_id: str) -> int:
        """Check login confirmation status"""
        url = f"https://www.zhipin.com/wapi/zppassport/qrcode/scanLogin?qrId={qr_id}&status=1"
        resp = session.get(url, timeout=60)
        return resp.status_code

    @staticmethod
    async def get_final_cookie(session: requests.Session, qr_id: str) -> tuple[str, str]:
        """Get final login cookie"""
        i_str = "8048b8676fb7d3d8952276e6e98e0bde.f2dc7a63c4b0fbfa4b51a07e2710cf83.fef7e750fc3a1e6327e8a880915aee9c.ae00f848beb1aa591d71d5a80dd3bd95"
        e_b64 = "clRwXUJBK1VKK0k0IWFbbQ=="

        fp = BossZhipinAPI.generate_fp(i_str, e_b64)

        dispatcher_url = f"https://www.zhipin.com/wapi/zppassport/qrcode/dispatcher?qrId={qr_id}&pk=header-login&fp={fp}"
        resp = session.get(dispatcher_url, allow_redirects=False)

        set_cookie_headers = resp.headers.get('Set-Cookie', '')
        cookie_str = ''
        bst_value = ''

        if set_cookie_headers:
            cookies = {}
            cookie_parts = set_cookie_headers.split(',')
            for part in cookie_parts:
                if '=' in part:
                    name_value = part.strip().split(';')[0].strip()
                    if '=' in name_value:
                        name, value = name_value.split('=', 1)
                        cookies[name.strip()] = value.strip()

            cookie_str = '; '.join([f"{k}={v}" for k, v in cookies.items()])

            if 'wt2' in cookies:
                cookie_str = f"wt2={cookies['wt2']}"
            if 'bst' in cookies:
                bst_value = cookies['bst']

        if cookie_str:
            session.headers['Cookie'] = cookie_str

        return cookie_str, bst_value

    # City name -> city code mapping (for lastCity cookie and search API)
    CITY_CODE_MAP = {
        '北京': '101010100',
        '上海': '101020100',
        '深圳': '101280600',
        '广州': '101280100',
        '杭州': '101210100',
        '成都': '101270100',
        '武汉': '101200100',
        '西安': '101110100',
        '南京': '101190100',
        '苏州': '101190400',
    }

    @staticmethod
    def _ensure_cookie_with_city(cookie: str, city_code: str) -> str:
        """Inject or override lastCity in cookie to reduce risk control (checked by site when pulling/searching jobs)"""
        if not city_code:
            return cookie
        if 'lastCity=' in cookie:
            return re.sub(r'lastCity=[^;]+', f'lastCity={city_code}', cookie)
        return cookie.rstrip('; ') + f'; lastCity={city_code}'

    @staticmethod
    def setup_api_headers(session: requests.Session, cookie: str, bst: str):
        """Set API request headers (general purpose, e.g., after login)"""
        session.headers.update({
            'Cookie': cookie,
            'zp_token': bst,
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
            'Referer': 'https://www.zhipin.com/web/user/?ka=header-login',
            'Origin': 'https://www.zhipin.com'
        })

    @staticmethod
    def setup_api_headers_for_job(
        session: requests.Session,
        cookie: str,
        bst: str,
        city_code: str = '101010100',
        referer_path: str = '/web/geek/job',
    ):
        """Set request headers for job pulling/searching, simulating user browsing job search page to reduce risk control"""
        cookie_with_city = BossZhipinAPI._ensure_cookie_with_city(cookie, city_code)
        base = 'https://www.zhipin.com'
        referer = base + referer_path if referer_path.startswith('/') else referer_path
        session.headers.update({
            'Cookie': cookie_with_city,
            'zp_token': bst,
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
            'Referer': referer,
            'Origin': base,
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8',
        })

    # Parameter mapping tables
    EXPERIENCE_MAP = {
        '在校生': 108,
        '应届生': 102,
        '不限': 101,
        '一年以内': 103,
        '一到三年': 104,
        '三到五年': 105,
        '五到十年': 106,
        '十年以上': 107
    }

    JOB_TYPE_MAP = {
        '全职': 1901,
        '兼职': 1903,
    }

    SALARY_MAP = {
        '3k以下': 402,
        '3-5k': 403,
        '5-10k': 404,
        '10-20k': 405,
        '20-50k': 406,
        '50以上': 407,
    }

    @staticmethod
    async def get_job_list(session: requests.Session, params: dict) -> dict:
        """Get job list"""
        url = "https://www.zhipin.com/wapi/zpgeek/pc/recommend/job/list.json"

        # Convert text params to codes
        converted_params = {}
        if 'experience' in params and params['experience'] in BossZhipinAPI.EXPERIENCE_MAP:
            converted_params['experience'] = BossZhipinAPI.EXPERIENCE_MAP[params['experience']]

        if 'jobType' in params and params['jobType'] in BossZhipinAPI.JOB_TYPE_MAP:
            converted_params['jobType'] = BossZhipinAPI.JOB_TYPE_MAP[params['jobType']]

        if 'salary' in params and params['salary'] in BossZhipinAPI.SALARY_MAP:
            converted_params['salary'] = BossZhipinAPI.SALARY_MAP[params['salary']]

        # Set default params
        default_params = {
            "page": 1,
            "pageSize": 15,
            "_": int(time.time() * 1000)  # Timestamp
        }
        default_params.update(converted_params)

        # Add other params (e.g., encryptExpectId)
        for key in ['page', 'pageSize', 'encryptExpectId']:
            if key in params:
                default_params[key] = params[key]

        try:
            resp = session.get(url, params=default_params, timeout=10)
            resp.raise_for_status()

            data = resp.json()

            if data.get("code") != 0:
                raise Exception(f"API error: {data.get('message', 'Unknown error')}")

            zp_data = data.get("zpData", {})
            job_list = zp_data.get("jobList", [])

            # Convert to standard format
            jobs = []
            for job in job_list:
                job_info = {
                    "securityId": job.get("securityId"),
                    "encryptBossId": job.get("encryptBossId"),
                    "jobDegree": job.get("jobDegree"),
                    "jobName": job.get("jobName"),
                    "lid": job.get("lid"),
                    "salaryDesc": job.get("salaryDesc"),
                    "jobLabels": job.get("jobLabels", []),
                    "skills": job.get("skills", []),
                    "jobExperience": job.get("jobExperience"),
                    "cityName": job.get("cityName"),
                    "areaDistrict": job.get("areaDistrict"),
                    "encryptBrandId": job.get("encryptBrandId"),
                    "brandName": job.get("brandName"),
                    "brandScaleName": job.get("brandScaleName"),
                    "industry": job.get("industry"),
                    "contact": job.get("contact", False),
                    "showTopPosition": job.get("showTopPosition", False)
                }
                jobs.append(job_info)

            return {
                "status": "success",
                "data": {
                    "hasMore": zp_data.get("hasMore", False),
                    "jobList": jobs,
                    "total": len(jobs)
                }
            }

        except requests.RequestException as e:
            return {
                "status": "error",
                "message": f"Network request failed: {str(e)}"
            }
        except Exception as e:
            return {
                "status": "error",
                "message": f"Failed to get jobs: {str(e)}"
            }

    @staticmethod
    async def get_job_list_search(
        session: requests.Session,
        params: dict,
    ) -> dict:
        """Search jobs by keyword (using search API with search page Referer to bypass risk control)"""
        url = "https://www.zhipin.com/wapi/zpgeek/search/joblist.json"
        query = params.get("query", "").strip()
        city_code = params.get("city", "101010100")
        page = params.get("page", 1)
        page_size = params.get("pageSize", 15)

        request_params = {
            "query": query,
            "city": city_code,
            "page": page,
            "pageSize": page_size,
            "_": int(time.time() * 1000),
        }
        if "experience" in params and params["experience"] in BossZhipinAPI.EXPERIENCE_MAP:
            request_params["experience"] = BossZhipinAPI.EXPERIENCE_MAP[params["experience"]]
        if "jobType" in params and params["jobType"] in BossZhipinAPI.JOB_TYPE_MAP:
            request_params["jobType"] = BossZhipinAPI.JOB_TYPE_MAP[params["jobType"]]
        if "salary" in params and params["salary"] in BossZhipinAPI.SALARY_MAP:
            request_params["salary"] = BossZhipinAPI.SALARY_MAP[params["salary"]]

        try:
            resp = session.get(url, params=request_params, timeout=15)
            resp.raise_for_status()
            data = resp.json()

            if data.get("code") != 0:
                raise Exception(f"API error: {data.get('message', 'Unknown error')}")

            zp_data = data.get("zpData", {})
            job_list = zp_data.get("jobList", [])

            jobs = []
            for job in job_list:
                job_info = {
                    "securityId": job.get("securityId"),
                    "encryptBossId": job.get("encryptBossId"),
                    "jobDegree": job.get("jobDegree"),
                    "jobName": job.get("jobName"),
                    "lid": job.get("lid"),
                    "salaryDesc": job.get("salaryDesc"),
                    "jobLabels": job.get("jobLabels", []),
                    "skills": job.get("skills", []),
                    "jobExperience": job.get("jobExperience"),
                    "cityName": job.get("cityName"),
                    "areaDistrict": job.get("areaDistrict"),
                    "encryptBrandId": job.get("encryptBrandId"),
                    "brandName": job.get("brandName"),
                    "brandScaleName": job.get("brandScaleName"),
                    "industry": job.get("industry"),
                    "contact": job.get("contact", False),
                    "showTopPosition": job.get("showTopPosition", False),
                }
                jobs.append(job_info)

            return {
                "status": "success",
                "data": {
                    "hasMore": zp_data.get("hasMore", False),
                    "jobList": jobs,
                    "total": len(jobs),
                },
            }
        except requests.RequestException as e:
            return {"status": "error", "message": f"Network request failed: {str(e)}"}
        except Exception as e:
            return {"status": "error", "message": f"Failed to search jobs: {str(e)}"}

    @staticmethod
    async def greet_boss(session: requests.Session, security_id: str, job_id: str) -> dict:
        """Send greeting to HR"""
        url = "https://www.zhipin.com/wapi/zpgeek/friend/add.json"

        params = {
            "securityId": security_id,
            "jobId": job_id
        }

        try:
            resp = session.get(url, params=params, timeout=10)
            resp.raise_for_status()

            data = resp.json()

            if data.get("code") != 0:
                raise Exception(f"API error: {data.get('message', 'Unknown error')}")

            zp_data = data.get("zpData", {})

            return {
                "status": "success",
                "message": "Greeting sent successfully",
                "data": {
                    "showGreeting": zp_data.get("showGreeting", False),
                    "securityId": zp_data.get("securityId"),
                    "bossSource": zp_data.get("bossSource"),
                    "source": zp_data.get("source"),
                    "encBossId": zp_data.get("encBossId")
                }
            }

        except requests.RequestException as e:
            return {
                "status": "error",
                "message": f"Network request failed: {str(e)}"
            }
        except Exception as e:
            return {
                "status": "error",
                "message": f"Failed to send greeting: {str(e)}"
            }


# Create FastMCP server instance
mcp = FastMCP(
    name="BossZhipin MCP Server"
)


@mcp.custom_route("/static/{filename:path}", methods=["GET"])
async def serve_static_file(request: Request) -> FileResponse:
    """Serve static files"""
    filename = request.path_params["filename"]
    file_path = state.static_dir / filename

    if file_path.exists() and file_path.is_file():
        return FileResponse(str(file_path))

    return JSONResponse(
        {"error": "File not found", "filename": filename},
        status_code=404
    )


@mcp.custom_route("/login/start", methods=["GET"])
async def http_login_start(request: Request):
    """HTTP trigger login: generate QR code, start background monitoring, return QR page URL"""
    try:
        state.reset_login()
        session = state.get_session()
        qr_id = BossZhipinAPI.get_randkey_sync(session)
        state.update_login_status(qr_id=qr_id, login_step="qr_generated")
        qr_image_data = BossZhipinAPI.get_qrcode_sync(session, qr_id)
        filename = f"qrcode_{qr_id}.png"
        filepath = state.static_dir / filename
        with open(filepath, "wb") as f:
            f.write(qr_image_data)
        image_url = f"http://127.0.0.1:8000/static/{filename}"
        state.update_login_status(image_url=image_url)
        monitor_thread = threading.Thread(target=background_scan_monitor, args=(qr_id,), daemon=True)
        monitor_thread.start()
        # Return simple HTML page showing QR code and instructions
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>BossZhipin QR Login</title>
<style>body{{font-family:sans-serif;text-align:center;padding:2rem;}} img{{max-width:280px;}} .tip{{color:#666;margin-top:1rem;}}</style></head>
<body>
<h2>BossZhipin QR Code Login</h2>
<p><img src="{image_url}" alt="QR Code"/></p>
<p class="tip">Please scan the QR code above with BossZhipin APP, then confirm login on your phone.</p>
<p class="tip">Login status is monitored automatically in the background.</p>
<p><a href="http://127.0.0.1:8000/login/start">Regenerate QR Code</a></p>
</body></html>"""
        return HTMLResponse(html)
    except Exception as e:
        return JSONResponse(
            {"status": "error", "message": str(e)},
            status_code=500
        )


@mcp.resource("boss://status")
async def get_server_status() -> str:
    """Get server status"""
    return json.dumps({
        "server": "BossZhipin MCP Server",
        "version": "2.0.0",
        "status": "running",
        "login_status": asdict(state.login_status)
    }, ensure_ascii=False, indent=2)


@mcp.resource("boss://config")
async def get_job_config() -> str:
    """Get job search configuration"""
    config = {
        "experience": BossZhipinAPI.EXPERIENCE_MAP,
        "jobType": BossZhipinAPI.JOB_TYPE_MAP,
        "salary": BossZhipinAPI.SALARY_MAP,
        "default_params": {
            "experience": "不限",
            "jobType": "全职",
            "salary": "不限",
            "page": 1
        }
    }
    return json.dumps(config, ensure_ascii=False, indent=2)


@mcp.resource("boss://login/start")
async def start_login(ctx: Context) -> str:
    """Start login flow"""
    try:
        await ctx.info("Starting BossZhipin login flow")

        state.reset_login()
        session = state.get_session()

        # Step 1: Get random key (sync version)
        qr_id = BossZhipinAPI.get_randkey_sync(session)
        state.update_login_status(qr_id=qr_id, login_step="qr_generated")

        # Step 2: Get QR code (sync version)
        qr_image_data = BossZhipinAPI.get_qrcode_sync(session, qr_id)

        # Save QR code image
        filename = f"qrcode_{qr_id}.png"
        filepath = state.static_dir / filename

        with open(filepath, "wb") as f:
            f.write(qr_image_data)

        # Generate image URL
        image_url = f"http://127.0.0.1:8000/static/{filename}"
        state.update_login_status(image_url=image_url)

        await ctx.info(f"QR code generated, QR ID: {qr_id}")

        return json.dumps({
            "status": "success",
            "message": "QR code generated, please visit the URL below to view the image",
            "qr_id": qr_id,
            "image_url": image_url,
            "login_step": "qr_generated"
        }, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Failed to start login: {str(e)}"
        await ctx.error(error_msg)
        state.update_login_status(error_message=error_msg)

        return json.dumps({
            "status": "error",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.resource("boss://login/info")
async def get_login_info(ctx: Context) -> str:
    """Get current login status and cookie info"""
    try:
        login_status = state.login_status

        result = {
            "is_logged_in": login_status.is_logged_in,
            "login_step": login_status.login_step,
            "qr_id": login_status.qr_id,
            "image_url": login_status.image_url,
            "error_message": login_status.error_message
        }

        if login_status.is_logged_in:
            result["cookie"] = login_status.cookie
            result["bst"] = login_status.bst

            if login_status.cookie:
                cookies_dict = {}
                for cookie_pair in login_status.cookie.split('; '):
                    if '=' in cookie_pair:
                        name, value = cookie_pair.split('=', 1)
                        cookies_dict[name] = value
                result["cookies_detail"] = cookies_dict

            await ctx.info("Logged in")
        else:
            await ctx.info(f"Current status: {login_status.login_step}")

        return json.dumps(result, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Failed to get login info: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "status": "error",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def login_full_auto(ctx: Context) -> str:
    """Fully automated login flow: generate QR code and monitor scan status in background (non-interactive)"""
    try:
        await ctx.info("Starting automated login flow")

        # Start login and generate QR code
        session = state.get_session()
        qr_id = await BossZhipinAPI.get_randkey(session)
        state.update_login_status(qr_id=qr_id, login_step="qr_generated")

        # Get QR code
        qr_image_data = await BossZhipinAPI.get_qrcode(session, qr_id)

        # Save QR code image
        filename = f"qrcode_{qr_id}.png"
        filepath = state.static_dir / filename

        with open(filepath, "wb") as f:
            f.write(qr_image_data)

        # Generate image URL
        image_url = f"http://127.0.0.1:8000/static/{filename}"
        state.update_login_status(image_url=image_url)

        # Start background thread to monitor scan status
        monitor_thread = threading.Thread(target=background_scan_monitor, args=(qr_id,), daemon=True)
        monitor_thread.start()

        await ctx.info(f"QR code generated: {image_url}")
        await ctx.info("Background monitor started, QR valid for 1 minute")

        return json.dumps({
            "status": "qr_generated",
            "message": "QR code generated, background monitor started",
            "qr_id": qr_id,
            "image_url": image_url,
            "login_step": "qr_generated",
            "next_action": "Please scan with BossZhipin APP, background will auto-monitor. Check boss-zp://login/info or get_login_info_tool for progress and cookie"
        }, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Auto login failed: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "status": "error",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def login_start_interactive(ctx: Context) -> str:
    """Interactive login flow: guide user through scan and confirmation"""
    try:
        await ctx.info("Starting interactive login flow")

        while True:  # Outer loop for full login retry
            while True:  # Inner loop for QR regeneration
                # Step 1: Start login and generate QR code
                session = state.get_session()
                qr_id = await BossZhipinAPI.get_randkey(session)
                state.update_login_status(qr_id=qr_id, login_step="qr_generated")

                # Get QR code
                qr_image_data = await BossZhipinAPI.get_qrcode(session, qr_id)

                # Save QR code image
                filename = f"qrcode_{qr_id}.png"
                filepath = state.static_dir / filename

                with open(filepath, "wb") as f:
                    f.write(qr_image_data)

                # Generate image URL
                image_url = f"http://127.0.0.1:8000/static/{filename}"
                state.update_login_status(image_url=image_url)

                # Display QR code info
                await ctx.info("=" * 50)
                await ctx.info("BossZhipin login QR code generated!")
                await ctx.info(f"QR Image URL: {image_url}")
                await ctx.info(f"QR ID: {qr_id}")
                await ctx.info("=" * 50)

                # Step 2: Ask user if scanned
                scan_result = await ctx.elicit(
                    "Please scan the QR code with BossZhipin APP, then select 'Scanned'",
                    response_type=["Scanned", "Regenerate QR", "Cancel Login"]
                )

                if scan_result.action != "accept" or scan_result.data not in ["Scanned", "Regenerate QR"]:
                    return json.dumps({
                        "status": "cancelled",
                        "message": "User cancelled login"
                    }, ensure_ascii=False, indent=2)

                if scan_result.data == "Regenerate QR":
                    await ctx.info("Regenerating QR code...")
                    state.reset_login()
                    continue

                # Step 3: Check scan status
                await ctx.info("Verifying scan status...")
                status_code = await BossZhipinAPI.check_scan_status(session, qr_id)

                if status_code == 200:
                    scan_check = {"status": "scanned"}
                elif status_code == 409:
                    scan_check = {"status": "waiting"}
                else:
                    scan_check = {"status": "error", "message": f"Unknown status: {status_code}"}

                if scan_check["status"] != "scanned":
                    await ctx.warning("Scan not detected, please confirm if scan was successful")
                    retry_result = await ctx.elicit(
                        "Rescan?",
                        response_type=["Rescan", "Continue Waiting", "Cancel Login"]
                    )

                    if retry_result.action != "accept" or retry_result.data == "Cancel Login":
                        return json.dumps({
                            "status": "cancelled",
                            "message": "User cancelled login"
                        }, ensure_ascii=False, indent=2)

                    if retry_result.data == "Rescan":
                        state.reset_login()
                        continue

                # Scan successful, exit inner loop
                break

            # Step 4: Wait for user confirmation on phone
            await ctx.info("Please confirm login on BossZhipin APP...")

            wait_messages = [
                "Waiting for confirmation...",
                "Waiting for user confirmation...",
                "Please tap confirm on your phone...",
                "Waiting for login confirmation..."
            ]

            login_success = False
            for i in range(60):  # Max 60 seconds wait
                message = wait_messages[i % len(wait_messages)]
                await ctx.info(f"{message} ({i+1}/60s)")

                # Check login confirmation status
                confirm_status_code = await BossZhipinAPI.check_login_confirmation(session, qr_id)

                if confirm_status_code == 200:
                    # Get final cookie
                    cookie_str, bst_value = await BossZhipinAPI.get_final_cookie(session, qr_id)

                    state.update_login_status(
                        is_logged_in=True,
                        cookie=cookie_str,
                        bst=bst_value,
                        login_step="logged_in"
                    )

                    confirm_result = {
                        "status": "logged_in",
                        "message": "Login successful!",
                        "has_cookie": True,
                        "has_bst": True,
                        "login_step": "logged_in"
                    }

                    await ctx.info("Login successful!")
                    return json.dumps(confirm_result, ensure_ascii=False, indent=2)
                elif confirm_status_code == 409:
                    await asyncio.sleep(1)
                    continue
                elif confirm_status_code == 408:
                    confirm_result = {"status": "timeout", "message": "Login confirmation timeout"}
                else:
                    confirm_result = {"status": "error", "message": f"Unknown confirmation status: {confirm_status_code}"}

                if confirm_result["status"] in ["timeout", "error"]:
                    await ctx.error(f"Login failed: {confirm_result['message']}")

                    retry_result = await ctx.elicit(
                        f"Login failed: {confirm_result['message']}. Restart login?",
                        response_type=["Restart Login", "Cancel"]
                    )

                    if retry_result.action == "accept" and retry_result.data == "Restart Login":
                        state.reset_login()
                        await ctx.info("Restarting login flow...")
                        break  # Exit current confirmation wait, restart outer loop
                    else:
                        return json.dumps({
                            "status": "cancelled",
                            "message": "User chose not to retry login"
                        }, ensure_ascii=False, indent=2)

            # If reached here, login timed out
            if not login_success:
                await ctx.warning("Confirmation timeout")
                timeout_result = await ctx.elicit(
                    "Confirmation timeout, restart login?",
                    response_type=["Restart Login", "Cancel"]
                )

                if timeout_result.action == "accept" and timeout_result.data == "Restart Login":
                    state.reset_login()
                    await ctx.info("Restarting login flow...")
                    continue  # Restart entire process
                else:
                    return json.dumps({
                        "status": "timeout",
                        "message": "Login timeout, user chose not to retry"
                    }, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Interactive login failed: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "status": "error",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def get_login_info(ctx: Context) -> str:
    """Tool to get current login status and cookie info"""
    try:
        login_status = state.login_status

        result = {
            "is_logged_in": login_status.is_logged_in,
            "login_step": login_status.login_step,
            "qr_id": login_status.qr_id,
            "image_url": login_status.image_url,
            "error_message": login_status.error_message
        }

        if login_status.is_logged_in:
            result["cookie"] = login_status.cookie
            result["bst"] = login_status.bst

            if login_status.cookie:
                cookies_dict = {}
                for cookie_pair in login_status.cookie.split('; '):
                    if '=' in cookie_pair:
                        name, value = cookie_pair.split('=', 1)
                        cookies_dict[name] = value
                result["cookies_detail"] = cookies_dict

            await ctx.info("Logged in, cookie info returned")
        else:
            await ctx.info(f"Current status: {login_status.login_step}")

        return json.dumps(result, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Failed to get login info: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "status": "error",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def get_recommend_jobs(
    ctx: Context,
    page: int = 1,
    experience: str = "不限",
    job_type: str = "全职",
    salary: str = "不限"
) -> str:
    """Get recommended jobs tool

    Args:
        page: Page number, starting from 1
        experience: Experience level, options: 在校生, 应届生, 不限, 一年以内, 一到三年, 三到五年, 五到十年, 十年以上
        job_type: Job type, options: 全职, 兼职
        salary: Salary range, options: 3k以下, 3-5k, 5-10k, 10-20k, 20-50k, 50以上
    """
    await ctx.info(f"Getting recommended jobs: page={page}")

    try:
        if not state.login_status.is_logged_in:
            return json.dumps({
                "error": "Not logged in",
                "message": "Please complete login before getting job info"
            }, ensure_ascii=False, indent=2)

        await ctx.info(f"Getting jobs: page={page}, experience={experience}, type={job_type}, salary={salary}")

        # Use job search page Referer and lastCity to reduce risk control
        session = state.get_session()
        BossZhipinAPI.setup_api_headers_for_job(
            session,
            state.login_status.cookie,
            state.login_status.bst,
            city_code='101010100',
            referer_path='/web/geek/job',
        )

        # Build API params
        params = {
            "page": page,
            "experience": experience,
            "jobType": job_type,
            "salary": salary
        }

        # Call real API
        result = await BossZhipinAPI.get_job_list(session, params)

        if result["status"] == "success":
            await ctx.info(f"Got {result['data']['total']} jobs")
            return json.dumps(result, ensure_ascii=False, indent=2)
        else:
            await ctx.error(f"Failed to get jobs: {result['message']}")
            return json.dumps({
                "error": "Failed to get jobs",
                "message": result["message"]
            }, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Failed to get jobs: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "error": "Failed to get jobs",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def search_jobs(
    ctx: Context,
    keyword: str,
    city: str = "北京",
    page: int = 1,
    experience: str = "不限",
    job_type: str = "全职",
    salary: str = "不限",
) -> str:
    """Search jobs by keyword (using search API to bypass risk control)

    Args:
        keyword: Search keyword, e.g., "Golang", "大模型", "Python"
        city: City, options: 北京, 上海, 深圳, 广州, 杭州, 成都, 武汉, 西安, 南京, 苏州
        page: Page number, starting from 1
        experience: Experience (在校生/应届生/不限/一年以内/一到三年/三到五年/五到十年/十年以上)
        job_type: Job type (全职/兼职)
        salary: Salary range (3k以下/3-5k/5-10k/10-20k/20-50k/50以上)
    """
    await ctx.info(f"Searching jobs by keyword: keyword={keyword}, city={city}, page={page}")

    try:
        if not state.login_status.is_logged_in:
            return json.dumps({
                "error": "Not logged in",
                "message": "Please complete login before searching jobs",
            }, ensure_ascii=False, indent=2)

        city_code = BossZhipinAPI.CITY_CODE_MAP.get(city, "101010100")
        referer_path = f"/web/geek/job?query={requests.utils.quote(keyword)}"

        session = state.get_session()
        BossZhipinAPI.setup_api_headers_for_job(
            session,
            state.login_status.cookie,
            state.login_status.bst,
            city_code=city_code,
            referer_path=referer_path,
        )

        params = {
            "query": keyword,
            "city": city_code,
            "page": page,
            "pageSize": 15,
            "experience": experience,
            "jobType": job_type,
            "salary": salary,
        }
        result = await BossZhipinAPI.get_job_list_search(session, params)

        if result["status"] == "success":
            await ctx.info(f"Search successful, found {result['data']['total']} jobs on this page")
            return json.dumps(result, ensure_ascii=False, indent=2)
        return json.dumps({
            "error": "Failed to search jobs",
            "message": result.get("message", "Unknown error"),
        }, ensure_ascii=False, indent=2)

    except Exception as e:
        return json.dumps({
            "error": "Failed to search jobs",
            "message": str(e),
        }, ensure_ascii=False, indent=2)


@mcp.tool()
async def send_greeting(
    ctx: Context,
    security_id: str,
    job_id: str,
    message: str = "您好，我对这个职位很感兴趣，希望可以进一步沟通"
) -> str:
    """Send greeting tool"""
    try:
        if not state.login_status.is_logged_in:
            return json.dumps({
                "error": "Not logged in",
                "message": "Please complete login before sending greeting"
            }, ensure_ascii=False, indent=2)

        await ctx.info(f"Sending greeting to job {job_id}")

        # Get session and set API headers
        session = state.get_session()
        BossZhipinAPI.setup_api_headers(session, state.login_status.cookie, state.login_status.bst)

        # Call real API
        result = await BossZhipinAPI.greet_boss(session, security_id, job_id)

        if result["status"] == "success":
            await ctx.info(f"Greeting sent successfully: {job_id}")
            return json.dumps(result, ensure_ascii=False, indent=2)
        else:
            await ctx.error(f"Failed to send greeting: {result['message']}")
            return json.dumps({
                "error": "Failed to send greeting",
                "message": result["message"]
            }, ensure_ascii=False, indent=2)

    except Exception as e:
        error_msg = f"Failed to send greeting: {str(e)}"
        await ctx.error(error_msg)
        return json.dumps({
            "error": "Failed to send greeting",
            "message": error_msg
        }, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    print("Starting Boss MCP Server...")
    print("Visit http://127.0.0.1:8000/mcp to connect to MCP server")
    print("Visit http://127.0.0.1:8000/static/ to view static files")

    # Run FastMCP server
    mcp.run(transport="streamable-http", host="127.0.0.1", port=8000)
